excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  
line_length: 160
 # they can set both implicitly with an array
type_body_length:
- 300 # warning
- 400 # error
file_length:
  warning: 500
  error: 1200
type_body_length:
  - 400 # warning
  - 500 # error